config/routes.rb
Rails.application.routes.draw do
  resource :welcome
  root to: "questions#index"

  devise_for :users 

  resources :users do
    resources :exam, controller: "examquestions"
    post "check_question", controller: "examquestions"
    #post "prev", controller: "examquestions"
    #get "next_question", controller: "examquestions" 
    #get "prev_question", controller: "examquestions" 
    #post "move_question", controller: "examquestions" 
  end

  resources :questions do
    resources :answers
  end

  get "results", controller: "examquestions"
  get "count_answer", controller: "questions"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, inverse_of: :answers, optional: true

  validates :give, length: { minimum: 1, maximum: 300, message: "Пожалуйста, введите ответ не меньше 1 и не более 300 символов"}
  validates :give,  presence: { message: "Поле ответа не может быть пустым" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
  validate :validate_correct_answer

  #belongs_to :question

  def validate_correct_answer
    self.question.errors.add(:base, "Пожалуйста, введите правильный ответ не меньше 1 и не более 1000 символов") if self.give.length > 1000 || self.give.length < 1
  end
end

app/models/create_exam_question.rb
class CreateExamQuestion < ApplicationRecord
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
  belongs_to :exam_question
end

app/models/exam_question.rb
class ExamQuestion < ApplicationRecord
  belongs_to :user
  has_many :exam_answers
end

app/models/question.rb
class Question < ApplicationRecord
  validates :ask, uniqueness: { message: "Такой вопрос уже существует"}
  validates :ask, length: { minimum: 5, maximum: 1000, message: "Пожалуйста, введите вопрос не меньше 5 и не более 1000 символов"}

  belongs_to :user

  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers

  #has_many :user_question_useranswers
  #has_many :users, through: :user_question_useranswers

  #has_many :user_question_useranswers
  #has_many :user_answers, through: :user_question_useranswers

  def prev_question(user)
    unless nil?
      index = user.questions.index(self)
      user.questions[index-1] if index > 0
    end
  end

  def next_question(user,user_answer)
    unless nil?
      index = user.questions.index(self)
      #user.questions[index].user_answers << UserAnswer.create(give: user_answer )
      user.user_question_useranswers[index].update(answer_user: user_answer)
      #user.user_question_useranswers[index].update(user_answer: UserAnswer.create(give: user_answer))
      user.questions[index+1] if index < user.questions.count - 1
    end
  end
end

app/models/questions_user.rb
class QuestionsUser < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  #has_many :user_question_useranswers
  #has_many :user_answers, through: :user_question_useranswers

  #has_many :user_question_useranswers
  #has_many :questions, through: :user_question_useranswers

  has_many :questions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  has_many :user_question_useranswers
  has_many :users, through: :user_question_useranswers

  has_many :user_question_useranswers
  has_many :questions, through: :user_question_useranswers
end

app/models/user_question_useranswer.rb
class UserQuestionUseranswer < ApplicationRecord

  belongs_to :question, optional: true
  belongs_to :user_answer, optional: true
  belongs_to :user, optional: true

end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [ :destroy ]

  def destroy
    @answer.destroy
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/examquestions_controller.rb
class ExamquestionsController < ApplicationController
  before_action :set_examquestion, only: [ :check_question ]

  def index
    @examquestions = Question.all.sample(9)
    if @examquestions.count == 9
      current_user.questions = @examquestions if current_user.questions.count < 9
    else
      flash.alert = "Questions not available, please contact course administrator"
    end
    @question = current_user.questions.first
  end

  def move_question
    current_index = current_user.questions.index(@examquestion)
    current_user.user_question_useranswers[current_index].update(user_answer: UserAnswer.create(give: 123))
  end

  def check_question
    @question = @examquestion.next_question(current_user, params[:answer]) if params[:next]
    @question = @examquestion.prev_question(current_user, params[:answer]) if params[:previous]
  end

  def results
    @users = User.all
  end

  private

  def set_examquestion
    @examquestion = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [ :show, :edit, :update, :destroy ]

  def index
    @questions = Question.all
    @user = current_user
  end

  def new
    @question = Question.new
    2.times { @question.answers.build}
  end

  def edit
  end

  def show
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    params[:question][:answers_attributes].each { |key,value| value.correct_answer = true if value[:correct_answer] == 1 }

    if @question.save
      redirect_to questions_path, notice: "Вопрос был успешно создан"
    else
      render 'new'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to questions_path, notice: "Вопрос был успешно обновлен"
    else
      render 'edit'
    end
  end

  def destroy
    if @question.destroy
      redirect_to questions_path, notice: "Вопрос был успешно удален"
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:ask, answers_attributes: [:id, :give, :_destroy, :correct_answer, :score])
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examquestion_helper.rb
module ExamquestionHelper
end

app/helpers/examquestions_helper.rb
module ExamquestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render questions/question.html.slim, question: @question %>');

app/views/examquestions/_form.html.slim
= render 'examquestions/question.html.slim', question: @question

app/views/examquestions/_question.html.slim
= div_for(question)
  = form_tag(user_check_question_path, method: 'post', remote: true, class: "question-form") do
    p.question_number= "Вопрос #{current_user.questions.index(question)+1} / #{current_user.questions.count}"
    p.description= question.ask
    br
    - if question.multiple_answers == false
      - question.answers.each do |answer|
        .answers
          = radio_button_tag(:answer, answer.id) 
          = label_tag(:answer, answer.give)
          br
          br
    - else
      .answers
        = collection_check_boxes('', :answer, question.answers, :id, :give) do |b|
          = b.label { b.check_box + b.text }
          br
          br

    = hidden_field_tag(:id, question.id)

    p= submit_tag "Prev", name: "previous"
    p= submit_tag "Next", name: "next"

app/views/examquestions/check_question.js.erb
<% unless @question.nil? %>
  $('#question_' + <%= @examquestion.id %>).html('<%= j render 'examquestions/question.html.slim', question: @question %>');
<% end %>

app/views/examquestions/index.html.slim
= render "form.html.slim"

app/views/examquestions/move_question.js.erb
$('#question_' + <%= @examquestion.id %>).html('<%= j render 'examquestions/question.html.slim', question: @question %>');

app/views/examquestions/results.html.slim
table
  thead
    tr
      th email
      th User answer
      th Score
  tbody
    - @users.each do |c|
      tr
        td = c.email
        td = c.examinee_answer
        td = c.examinee_score

app/views/questions/_answers.html.slim
p= f.fields_for :answers do |answers_form|
  p= answers_form.label :give, 'Ответ'
  p= answers_form.text_area :give, size: "100x1"
  p
  = answers_form.check_box :correct_answer, { checked: answers_form.object.correct_answer? }
  = answers_form.label :correct_answer, "Правильный ответ"
  p
  = answers_form.text_field :score
  = answers_form.label :score, "Баллов за ответ"
  p
  = link_to "Delete answer", question_answer_path(@question, answers_form.object), method: :delete, remote: true if @question.answers.size > 2

app/views/questions/_errors.html.slim
- if @question.errors.any?
    #error_explanation
      h2
        = "Обнаружены ошибки"
      ul
        - @question.errors.full_messages.each do |msg|
          li #{msg}

app/views/questions/_question.html.slim
= form_for question  do |f|
  = render "errors"
  
  p= f.label :ask, 'Вопрос:'
  p= f.text_area :ask, size: "100x6"

  p= "Варианты ответов"

  div class="answers"
    p= f.fields_for :answers do |answers_form|
      p= answers_form.label :give, 'Ответ'
      p= answers_form.text_area :give, size: "100x1"
      p
      = answers_form.check_box :correct_answer, { checked: answers_form.object.correct_answer? }
      = answers_form.label :correct_answer, "Правильный ответ"
      p
      = answers_form.text_field :score
      = answers_form.label :score, "Баллов за ответ"
      p
      = link_to "Delete answer", question_answer_path(@question, answers_form.object), method: :delete, remote: true if @question.answers.size > 2

  p= link_to "Добавить ответ", count_answer_path, remote: true
  p= f.submit question.new_record? ? 'Сохранить' : 'Обновить'

app/views/questions/destroy.js.erb
$('#question_' + <%= @question.id %>).remove();

app/views/questions/edit.html.slim
= render @question

app/views/questions/index.html.slim
p= link_to 'Создать вопрос', new_question_path
p= link_to "#{current_user.questions.empty? ? 'Начать экзамен' : 'Продолжить экзамен' }", user_exam_index_path(user_id: @user.id) if user_signed_in?
p= link_to 'Show results', results_path

div class='myquestions'
- @user.questions.each do |question|
  p= question.ask
  p= link_to 'Show', question_path(question)
  p= link_to 'Edit', edit_question_path(question)
  p= link_to 'Delete', question_path(question), data: { confirm: 'Are you sure?' }, method: :delete 

app/views/questions/new.html.slim
= render @question

app/views/questions/show.html.slim
p= "Question:"
p= @question.ask
p= "Answers:"
- @question.answers.each do |answer|
  ul
    li
      = answer.give
p= link_to 'Edit', edit_question_path(@question)